import type { CodexItem, CodexMonster } from "./codex-types";

export const CODEX_ITEMS: CodexItem[] = [
  {
    id: "item-fly-wing",
    type: "item",
    name: "Fly Wing",
    category: "usable",
    description: "A wing that teleports the user to a random point on the current map.",
    weight: 20,
    effects: ["Random teleport within current map"],
    tags: ["popular"],
  },
  {
    id: "item-butterfly-wing",
    type: "item",
    name: "Butterfly Wing",
    category: "usable",
    description: "A wing that teleports the user to their saved save point.",
    weight: 30,
    effects: ["Teleport to saved save point"],
    tags: ["popular"],
  },
  {
    id: "item-yggdrasil-berry",
    type: "item",
    name: "Yggdrasil Berry",
    category: "consumable",
    description: "A berry from the World Tree that fully restores HP and SP.",
    weight: 30,
    effects: ["Restore 100% HP", "Restore 100% SP"],
    tags: ["popular", "buff"],
  },
  {
    id: "item-white-potion",
    type: "item",
    name: "White Potion",
    category: "consumable",
    description: "A potion that restores a moderate amount of HP.",
    weight: 10,
    effects: ["Restore ~325 HP"],
    tags: ["popular"],
  },
  {
    id: "item-guillotine-cross-card",
    type: "item",
    name: "Guillotine Cross Card",
    category: "card",
    slot: "weapon",
    description: "A card imbued with the spirit of a Guillotine Cross.",
    effects: ["Critical damage +10%", "ASP +5%"],
    tags: ["equipment", "popular"],
  },
  {
    id: "item-arch-bishop-card",
    type: "item",
    name: "Arch Bishop Card",
    category: "card",
    slot: "armor",
    description: "A card imbued with the spirit of an Arch Bishop.",
    effects: ["Healing effectiveness +5%", "Max HP +10%"],
    tags: ["equipment", "popular"],
  },
  {
    id: "item-windhawk-card",
    type: "item",
    name: "Windhawk Card",
    category: "card",
    slot: "weapon",
    description: "A card imbued with the spirit of a Windhawk.",
    effects: ["Ranged damage +10%", "ASPD +5%"],
    tags: ["equipment", "popular"],
  },
  {
    id: "item-cenlab-orb",
    type: "item",
    name: "Cenia's Orb",
    category: "etc",
    description: "A mysterious orb dropped in the Central Laboratory. Used for crafting and exchange.",
    weight: 1,
    sources: ["Central Laboratory bosses"],
    tags: ["central-lab", "drop"],
  },
  {
    id: "item-cenlab-core",
    type: "item",
    name: "Laboratory Core",
    category: "etc",
    description: "A power core recovered from the Central Laboratory machinery.",
    weight: 5,
    sources: ["Central Laboratory"],
    tags: ["central-lab", "drop"],
  },
  {
    id: "item-ogch-token",
    type: "item",
    name: "OGCH Token",
    category: "etc",
    description: "A token earned from the Old Glast Heim Challenge. Used to exchange for gear.",
    weight: 0,
    sources: ["Old Glast Heim Challenge"],
    tags: ["ogch", "drop", "quest"],
  },
  {
    id: "item-ogch-armor",
    type: "item",
    name: "Temporal Armor",
    category: "armor",
    slot: "armor",
    description: "A powerful armor forged with temporal energy from Old Glast Heim.",
    equipLevel: 99,
    refineable: true,
    slots: 1,
    effects: ["Max HP +20%", "Variable cast time -10%"],
    sources: ["Old Glast Heim Challenge exchange"],
    tags: ["ogch", "equipment", "popular"],
  },
  {
    id: "item-water-dungeon-essence",
    type: "item",
    name: "Aqua Essence",
    category: "etc",
    description: "Pure water essence collected from the sunken tower.",
    weight: 1,
    sources: ["Water Dungeon"],
    tags: ["water-dungeon", "drop", "quest"],
  },
  {
    id: "item-water-dungeon-weapon",
    type: "item",
    name: "Trident of the Abyss",
    category: "weapon",
    slot: "weapon",
    description: "A trident infused with abyssal water magic.",
    equipLevel: 150,
    refineable: true,
    slots: 2,
    effects: ["Water magic damage +15%", "MATK +100"],
    sources: ["Water Dungeon boss"],
    tags: ["water-dungeon", "equipment", "boss"],
  },
  {
    id: "item-megalith-card",
    type: "item",
    name: "Megalith Card",
    category: "card",
    slot: "shield",
    description: "Grants the toughness of stone.",
    effects: ["DEF +50", "VIT +3"],
    tags: ["equipment"],
  },
  {
    id: "item-ambernite-card",
    type: "item",
    name: "Ambernite Card",
    category: "card",
    slot: "armor",
    description: "A card carrying the defensive shell of an Ambernite.",
    effects: ["DEF +50"],
    tags: ["equipment"],
  },
  {
    id: "item-berserk-potion",
    type: "item",
    name: "Berserk Potion",
    category: "consumable",
    description: "Greatly increases attack speed and attack power for a short duration.",
    weight: 20,
    effects: ["ASPD +20%", "ATK +30"],
    tags: ["buff", "popular"],
  },
];

export const CODEX_MONSTERS: CodexMonster[] = [
  {
    id: "monster-poring",
    type: "monster",
    name: "Poring",
    level: 1,
    race: "plant",
    element: "water",
    elementLevel: 1,
    size: "medium",
    hp: 60,
    baseExp: 5,
    jobExp: 2,
    drops: [
      { itemId: "item-jellopy", itemName: "Jellopy" },
      { itemId: "item-knife", itemName: "Knife" },
    ],
    locations: ["Prontera Fields", "Payon Forest"],
    tags: ["popular"],
  },
  {
    id: "monster-lunatic",
    type: "monster",
    name: "Lunatic",
    level: 3,
    race: "brute",
    element: "neutral",
    elementLevel: 1,
    size: "small",
    hp: 97,
    baseExp: 6,
    jobExp: 3,
    drops: [{ itemId: "item-clover", itemName: "Clover" }],
    locations: ["Prontera Fields"],
    tags: ["popular"],
  },
  {
    id: "monster-cenia",
    type: "monster",
    name: "Cenia",
    level: 175,
    race: "demihuman",
    element: "neutral",
    elementLevel: 2,
    size: "medium",
    hp: 250000000,
    baseExp: 500000,
    jobExp: 350000,
    drops: [
      { itemId: "item-cenlab-orb", itemName: "Cenia's Orb" },
      { itemId: "item-cenlab-core", itemName: "Laboratory Core" },
    ],
    locations: ["Central Laboratory"],
    isMvp: true,
    tags: ["central-lab", "boss", "mvp"],
  },
  {
    id: "monster-cenelia",
    type: "monster",
    name: "Cenelia",
    level: 175,
    race: "demihuman",
    element: "fire",
    elementLevel: 2,
    size: "medium",
    hp: 230000000,
    baseExp: 480000,
    jobExp: 330000,
    drops: [
      { itemId: "item-cenlab-orb", itemName: "Cenia's Orb" },
      { itemId: "item-cenlab-core", itemName: "Laboratory Core" },
    ],
    locations: ["Central Laboratory"],
    isMvp: true,
    tags: ["central-lab", "boss", "mvp"],
  },
  {
    id: "monster-ogch-boss",
    type: "monster",
    name: "Amdarais",
    level: 160,
    race: "demon",
    element: "undead",
    elementLevel: 3,
    size: "large",
    hp: 800000000,
    baseExp: 1200000,
    jobExp: 800000,
    drops: [
      { itemId: "item-ogch-token", itemName: "OGCH Token" },
      { itemId: "item-ogch-armor", itemName: "Temporal Armor" },
    ],
    locations: ["Old Glast Heim Challenge"],
    isMvp: true,
    tags: ["ogch", "boss", "mvp"],
  },
  {
    id: "monster-water-boss",
    type: "monster",
    name: "Kraken",
    level: 165,
    race: "fish",
    element: "water",
    elementLevel: 3,
    size: "large",
    hp: 450000000,
    baseExp: 900000,
    jobExp: 600000,
    drops: [
      { itemId: "item-water-dungeon-essence", itemName: "Aqua Essence" },
      { itemId: "item-water-dungeon-weapon", itemName: "Trident of the Abyss" },
    ],
    locations: ["Water Dungeon"],
    isMvp: true,
    tags: ["water-dungeon", "boss", "mvp"],
  },
  {
    id: "monster-megalith",
    type: "monster",
    name: "Megalith",
    level: 35,
    race: "formless",
    element: "neutral",
    elementLevel: 1,
    size: "large",
    hp: 3000,
    baseExp: 350,
    jobExp: 200,
    drops: [{ itemId: "item-megalith-card", itemName: "Megalith Card" }],
    locations: ["Moria"],
    tags: ["drop"],
  },
  {
    id: "monster-ambernite",
    type: "monster",
    name: "Ambernite",
    level: 25,
    race: "insect",
    element: "water",
    elementLevel: 1,
    size: "medium",
    hp: 1500,
    baseExp: 180,
    jobExp: 120,
    drops: [{ itemId: "item-ambernite-card", itemName: "Ambernite Card" }],
    locations: ["Payon Cave"],
    tags: ["drop"],
  },
  {
    id: "monster-baphomet",
    type: "monster",
    name: "Baphomet",
    level: 81,
    race: "demon",
    element: "shadow",
    elementLevel: 3,
    size: "large",
    hp: 668000,
    baseExp: 118800,
    jobExp: 89100,
    drops: [
      { itemId: "item-baphomet-card", itemName: "Baphomet Card" },
      { itemId: "item-baphomet-horn", itemName: "Baphomet Horn" },
    ],
    locations: ["Labyrinth"],
    isMvp: true,
    tags: ["boss", "mvp", "popular"],
  },
  {
    id: "monster-mistress",
    type: "monster",
    name: "Mistress",
    level: 77,
    race: "insect",
    element: "wind",
    elementLevel: 3,
    size: "medium",
    hp: 578000,
    baseExp: 96800,
    jobExp: 72600,
    drops: [
      { itemId: "item-mistress-card", itemName: "Mistress Card" },
      { itemId: "item-corsage", itemName: "Corsage" },
    ],
    locations: ["Mjolnir Dead Pit"],
    isMvp: true,
    tags: ["boss", "mvp", "popular"],
  },
];

export const ALL_CODEX_ENTRIES = [...CODEX_ITEMS, ...CODEX_MONSTERS];
